### ISSUE TITLE
Consider adding a license

### ISSUE THREAD

**Issue by torkleyy** [AngelOnFira/rusty-christmas-tree#6]
Hello, thanks for sharing this awesome project!

I noticed the repository doesn't contain any license. This makes it legally impossible to use or contribute to the repo. GitHub lets you add the most common ones from the Insights -> Community tab I believe.

Thanks for considering! 🎄

**Comment by AngelOnFira** [comment]
Yup, thanks for pointing it out, this was just an oversight from me :)
