### ISSUE TITLE
Re-licensing under MIT/Apache 2

### ISSUE THREAD

**Issue by AngelOnFira** [AngelOnFira/rusty-christmas-tree#7]
@ApprenticeofEnder @EliasJRH @ayyEve I forgot to add a license originally, so we get to do a re-license :tada: 

To agree to have your code re-licensed under the dual MIT/Apache-2.0 license, reply to this issue with the comment below :+1: (if you don't agree to the re-license, commend that and I'll remove your code from the repo)

```
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.
```

**Comment by AngelOnFira** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by ApprenticeofEnder** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by ayyEve** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by EliasJRH** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.
